export default [
  "Everyone go and drink a sip of water. -Compositr, Lemon Tools Dev",
  "Send a random DM to the first person in your friends list",
  "Let the group decide what PFP you have for the next day",
  "Let the group decide what PFP you have for the next week",
  "Let the group nickname you in this server to whatever they want",
  "Do your best impression of someone else in the group",
  "Link everyone to the last song you played",
  "Link everyone to your favourite playlist",
  "Show everyone the first 10 people on your friends list",
  "Show everyone the first 10 people on your block list",
  "Write a poem using the words orange and moose at least once each",
  "Text someone in the group, and the group has to guess who you texted",
  "Let someone in the group change your status",
  "Do an impression of someone else until the group finds out who it is",
  "Try your best to imiate a British accent",
  "GET DOWN AND GIMME 20 - Lemon Tools Dev Team",
  "Eat an ice cube",
  "In the next 10 minutes, try to scare someone",
  "The group asks you a question. You must answer."
] as const;
