// Do not edit this file unless you know what you are doing!
// Just stay on the safe side and don't edit
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      BOT_TOKEN?: string;
      ENVIRONMENT: "dev" | "production" | "debug";
      TEST_GUILD: string;
      APPLICATION_ID: string;
      NASA: string;
      MONGO: string;
      NYT: string;
      ORG: string;
      BUCKET: string;
      INFLUX: string;
      INFLUX_URL: string;
      LISTENER_PORT: number;
      LISTENER_SECRET: string;
      TOPGG_TOKEN: string;
    }
  }
}

export {}; // Empty export to avoid errors which sometimes occur
