export default [
  "What was the most embarassing moment of your life?",
  "Who is the ugliest out of everyone playing in your opinion?",
  "How often do you bathe?",
  "When was the last time you cried?",
  "What is the most embarassing thing you have done?",
  "What is your favourite sport",
  "What is your favourite food?",
  "What is your favourite drink?",
  "What is your favourite colour?",
  "What is your favourite animal?",
  "If you had a billion dollars all of a sudden, how would you spend it",
  "What is your favourite song?",
  "What is something you haven't said to anyone else? Say that now",
  "Tell the group what your last dream was about",
  "What is your favourite thing to do in your free time?",
  "State the dumbest thing you have ever done",
  "If you could become a fictional character for one day, who would it be?",
] as const;
