// Generated by https://quicktype.io

export interface MCPlayer {
  id:         string;
  name:       string;
  properties: Property[];
  error?: string
}

export interface Property {
  name:  string;
  value: string;
}
