// Generated by https://quicktype.io

export interface NYTSectionHeadlines {
  status:       string;
  copyright:    string;
  section:      string;
  last_updated: string;
  num_results:  number;
  results:      Result[];
}

export interface Result {
  section:             string;
  subsection:          Subsection;
  title:               string;
  abstract:            string;
  url:                 string;
  uri:                 string;
  byline:              string;
  item_type:           ItemType;
  updated_date:        string;
  created_date:        string;
  published_date:      string;
  material_type_facet: string;
  kicker:              string;
  des_facet:           string[];
  org_facet:           string[];
  per_facet:           string[];
  geo_facet:           string[];
  multimedia:          Multimedia[];
  short_url:           string;
}

export enum ItemType {
  Article = "Article",
  Interactive = "Interactive",
  Promo = "Promo",
}

export interface Multimedia {
  url:       string;
  format:    Format;
  height:    number;
  width:     number;
  type:      Type;
  subtype:   Subtype;
  caption:   string;
  copyright: string;
}

export enum Format {
  SuperJumbo = "superJumbo",
}

export enum Subtype {
  Photo = "photo",
}

export enum Type {
  Image = "image",
}

export enum Subsection {
  Dance = "dance",
  Design = "design",
  Empty = "",
  Music = "music",
  Review = "review",
  Television = "television",
}
